# Generated by Django 6.0.1 on 2026-01-15 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal'), ('evaluable', 'Evaluable')], max_length=20)),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('completada', models.BooleanField(default=False)),
                ('validada_profe', models.BooleanField(default=False)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='tareas_grupales', to=settings.AUTH_USER_MODEL)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
